$NetBSD: patch-pyproject.toml,v 1.1 2022/02/01 18:43:17 schmonz Exp $

Avoid setuptools_scm since tarball has no .git.

--- pyproject.toml.orig	2022-02-01 02:24:32.000000000 +0000
+++ pyproject.toml
@@ -7,7 +7,6 @@ module = [
   "html2text",
   "pytest",
   "requests_file",
-  "setuptools_scm",
   "unidecode",
   "xdg",
   "xdg.BaseDirectory",
@@ -15,7 +14,4 @@ module = [
 ignore_missing_imports = true
 
 [build-system]
-requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]
-
-[tool.setuptools_scm]
-write_to = "feed2exec/_version.py"
+requires = ["setuptools>=45", "wheel"]
